
package com.ingenium.camira.retrieval.chileautos;

import com.google.common.collect.ImmutableList;

import java.util.List;

public class Constants {
  
  public static final List<String> vehicleTypes = ImmutableList.of("Todos",
      "Acuáticos", "Autos, camionetas y 4x4", "Bicicletas", "Buses", "Camiones",
      "Maquinarias", "Motorhomes", "Otros");
  
  public static final List<String> regions = ImmutableList.of("Antofagasta",
      "Araucanía", "Arica y Parinacota", "Atacama", "Aysén", "Bío Bío",
      "Coquimbo", "Los Lagos", "Los Ríos", "Magallanes y Antártica Chilena",
      "Maule", "Metropolitana de Santiago", "OHiggins", "Tarapacá",
      "Valparaíso");
  
  public static final List<String> brands = ImmutableList.of("Abat", "Acadian",
      "Acura", "Adventure", "Aerovan", "Africa", "Agrale", "Agria", "Agromaq",
      "Agusta", "AJS", "Alfa Romeo", "Allmand", "Altec", "Amazone", "Ammann",
      "Anderson Trailers", "Antonio Carraro", "Aprilia", "APT", "Aqualine",
      "Arctic Cat", "Aro", "Artigiana", "ASIA", "Aston Martin", "Atlas",
      "Atlas Copco", "ATV", "AUDI", "Ausa", "Austin", "Autorrad", "Aventura",
      "BAIC", "Bajaj", "Baldan", "Barford", "Barko", "Bartell", "Bashan", "BAW",
      "Bayliner", "Beiben", "Belarus", "Benelli", "Benford", "Benneteau",
      "Bentley", "BMW", "Bobcat", "Bomag", "Bombard", "Bonluck", "Breviglieri",
      "Brilliance", "BRP CAN-AM", "Buell", "Buggy", "Buick", "Busscar", "BYD",
      "Caburga", "Cadillac", "Caio", "Caky", "Can-Am", "Canoa", "Carmix",
      "Case", "Catalina", "Caterpillar", "CF Moto", "CGB Trailer", "Challenger",
      "Champion", "Chandler", "Changan", "Changlin", "Chaparral", "Chery",
      "CHEVORLET", "Chevrolet", "Choice", "Chris Craft", "Chrysler", "CITROEN",
      "Claas", "Coachmen", "Cobalt", "Coleman", "Coloso", "Comil", "Compair",
      "Craftsman", "CRG", "Cross", "Crucero", "Cukurova", "Cummins", "Daewoo",
      "Daf", "Daihatsu", "Datsun", "Demag", "Deutz-Fahr", "DFM", "DFSK",
      "Dimex", "Dingli", "Dingo", "Divermaq", "DKW", "Dodge", "Dongfeng",
      "Doosan", "Doyayama", "DS", "Ducar", "DUCATI", "E-One", "Eager Beaver",
      "Elho", "Euromot", "Europard", "Exel", "FACCHINI", "Falc", "Farmtrac",
      "Fassi", "Faw", "Feri", "Fernández", "Ferrari", "Fiat", "Fiatallis",
      "Fibermold", "Fleewood", "Ford", "Forest River", "Forway", "Foton",
      "Four Winns", "Freightliner", "Fruehauf", "Fullcar", "Fuso", "GAC GONOW",
      "GAC MOTOR", "Gama", "Garant Kotte", "Gas Gas", "Gaspardo", "GEELY",
      "Genie", "Geo", "Giant", "Gilera", "Glastron", "GMC", "Golden Dragon",
      "Goldini", "Goren", "Great Dane", "Great Wall", "Gribaldi Salvia",
      "Grimme", "Grove", "Guzzi", "Hafei", "Haima", "Hamm", "Hardi",
      "Harley-Davidson", "Haulotte", "HAVAL", "Heartland", "Hechizo", "Heli",
      "Hidromek", "Higer", "Hino", "Hisun", "Hitachi", "Hodar", "HONDA",
      "Honex", "Howard", "Huanghai - SG", "Huatai", "Hudson", "Hummer",
      "Hunter", "Husaberg", "Husqvarna", "Hyosung", "Hyster", "Hyundai",
      "Indian", "Indusa", "Infiniti", "Ingersoll Rand", "Inrecar",
      "International", "Invermoto", "Irizar", "Islander", "Isuzu", "Iveco",
      "Ivesa", "JAC", "Jacto", "JAGUAR", "Jayco", "JBC", "JCB", "Jeanneau",
      "Jeep", "JF", "Jinbei", "Jinlun", "Jinma", "JLG", "JMC", "John Deere",
      "Jota Boats", "Jumil", "Jurmar", "Kamaz", "Kaufman", "Kawasaki", "Keeway",
      "Kenworth", "Keystone", "KIA", "King Long", "Kinlon", "Kobelco",
      "Komatsu", "Krone", "KTM", "Kubota", "Kuhn", "Kvernerland", "Kymco",
      "Lada", "Lamborghini", "Lambretta", "Lancia", "LAND ROVER", "Landini",
      "LANDWIND", "Lemken", "Lerpain", "Lexus", "Librelato", "Liebherr",
      "Lifan", "Lifeng Group", "Lihhai", "Lincoln", "Linde", "Link-Belt",
      "Liugong", "LML", "Loncin", "Lonking", "Lotus", "MacGregor", "Machile",
      "Mack", "Magirus Deutz", "Mahindra", "Malbec", "Man", "Manitou", "Mapar",
      "Mapel", "Marchesan", "Marcopolo", "Mariah", "Mariner", "Mascarello",
      "Maserati", "Masmetal", "Massey ferguson", "Master Tow", "Mastracchio",
      "Maxibus", "Maximal", "Maxum", "Maxus", "Mazda", "McLaren", "Megelli",
      "Mercedes Benz", "Mercruiser", "Mercury", "Meridian", "Metalpar",
      "Metaltec", "MG", "Michigan", "MINI", "Mits", "Mitsubishi", "MJ", "Monon",
      "Monosem", "Montenegro", "Monterrey", "Morris", "Motar", "Moto ABC",
      "Motoguzzi", "Motomel", "Motorhome", "Motorrad", "MSK", "Mussre",
      "Mustang", "MV Agusta", "National Crane", "Nautic", "Nauticat",
      "Nautisail", "New Holland", "Nissan", "Nissan Cidef", "Nissan Marubeni",
      "Nordkapp", "NSU", "Oday", "Oldsmobile", "Opel", "Oxford", "Packard",
      "Palfinger", "Pegaso", "Perforadora Lobos", "PEUGEOT", "PGO", "Piaggio",
      "Pilot", "Pit Bike", "PKM", "Plymouth", "PM", "Polaris", "Pontiac",
      "PORSCHE", "Pottinger", "Pramac", "Prentice", "PROTON", "Putzmeister",
      "PYH", "PZ", "Quality Services Ltd", "RAM", "Randon", "Range Rover",
      "Ranger", "Rauch", "Regal", "Regal Raptor", "Remolques Tapia", "RENAULT",
      "Renault-Samsung", "Robot", "Rochel", "Rockwood", "ROLLS ROYCE",
      "Rondini", "Rotax", "Rover", "Royal Enfield", "Saab", "Sachs", "Saleen",
      "Same", "Samsung", "Sandvik", "Sanlg", "Sargent Agricola", "Saturn",
      "Scania", "SDLG", "Sea-Doo", "Sea-Ray", "SEAT", "Semirigido", "Shacman",
      "Shangai", "Shantui", "Shelby", "Shenyang", "Shifeng", "Simca",
      "Sinotruck", "Ski-Doo", "Skoda", "Skygo", "SMA", "Smart", "Spitz",
      "Sport Voad", "Sportbas", "Ssangyong", "Standard", "Stara",
      "Starcraft RV", "Sterling", "Stingray", "Strike", "Studebaker", "SUBARU",
      "SULKY", "Sullivan", "Super Hawai", "Super Products", "Surco", "SUZUKI",
      "SYM", "Tahoe", "Takasaki", "Tartan", "Tata", "Tatu", "TCM", "Tecnomad",
      "Terex", "Thompson", "Thwaites", "TM", "Tohatsu", "Toyota", "Trailer",
      "Travin", "Trayers", "Trek", "Tremac", "Triumph", "TWG Trailer",
      "United Motors", "Universal", "Ural", "Utility", "Valfamaq", "Valmet",
      "Valtra", "Vento", "Vermeer", "Vespa", "Vicon", "Volare", "Volkswagen",
      "VOLVO", "Wabash", "Wagner", "Walker Bay", "Wanch", "Wangye", "Wellcraft",
      "Westerly", "Western Star", "Willys", "Winnebago", "Wolken", "Wuhlmaus",
      "Wuzhoulong", "XBH", "XCMG", "XGMA", "XINGYUE", "Xpress International",
      "Yadea", "Yale", "Yamaha", "Yanmar", "Yingang", "Yinxiang", "Yomel",
      "Yougman", "Youyi", "YTO", "Yuchai", "Yuejin", "Yutong", "Zastava",
      "Zero", "Zetor", "Zhongtong", "ZNA", "Znen Group", "Zodiac", "Zongshen",
      "ZOTYE", "ZXAuto");
  
}
